apiVersion: v1
kind: Service
metadata:
  name: benchmarkservice-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-056abb18d2b063dcf,subnet-0989548712ae39f8c,subnet-0fbfc53e9beac2388
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
spec:
  loadBalancerClass: service.k8s.aws/nlb
  allocateLoadBalancerNodePorts: false
  loadBalancerSourceRanges: [0.0.0.0/0]
