apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../kubernetes-manifests
- client-config.yaml
images:
- name: adservice
  newName: matslo123/adservice
  newTag: v0.7.0
  digest: sha256:3856d1a4302a98e4a39e4be1e9e7995c315e177fc028fd5eb8542a4c33394fac
- name: benchmarkservice
  newName: matslo123/benchmarkservice
  newTag: v0.7.0
  digest: sha256:53b4b74848ff39536162c328b1b6a24b9386b7cde5db8967dabd7a4c2396b477
- name: cartservice
  newName: matslo123/cartservice
  newTag: v0.7.0
  digest: sha256:98812d26da5f93a29cffc8aa93801fb7b82517b703bade18876033385061c3a0
- name: checkoutservice
  newName: matslo123/checkoutservice
  newTag: v0.7.0
  digest: sha256:14374b110125e8ce183db256c1357d98a1ae1769fca01a61c13267979dd34b0d
- name: currencyservice
  newName: matslo123/currencyservice
  newTag: v0.7.0
  digest: sha256:1b676e316bfbb845411f4b5b02f376b780fe2ca3614c8a84065aa4a06be608f6
- name: emailservice
  newName: matslo123/emailservice
  newTag: v0.7.0
  digest: sha256:bff27de63900bb605ffa8082776fd866f65f56831fc15da72e6f62c29679c619
- name: frontend
  newName: matslo123/frontend
  newTag: v0.7.0
  digest: sha256:7d659542349ad1bf9ff80399a5f99f4af83c4bd4360b4e4e43f9e119e53ba2fd
- name: messageoperationsservice
  newName: matslo123/messageoperationsservice
  newTag: v0.7.0
  digest: sha256:07abbd1a93fd51c9092f347d3d34bb58bc5a848ece8524d2a092105968d12b1f
- name: paymentservice
  newName: matslo123/paymentservice
  newTag: v0.7.0
  digest: sha256:48b79ac7ecf5aa4f302599a3cf0738f14c4f368c76cccbcef3185bbb51e950cd
- name: productcatalogservice
  newName: matslo123/productcatalogservice
  newTag: v0.7.0
  digest: sha256:26d97784a6e105cf1586b2ff723772c583021491d5fa165ceaae6a3af12fe54d
- name: recommendationservice
  newName: matslo123/recommendationservice
  newTag: v0.7.0
  digest: sha256:7c056ea623ea3964eee7f21b7c4cc5e100d24abafeb3fe9f7b91ae26caa0544b
- name: shippingservice
  newName: matslo123/shippingservice
  newTag: v0.7.0
  digest: sha256:d8c1054bf40a9df1917249358c272239a7685f12f9ce625d5aa5d9e0f2a3aeba
- name: storefrontprojectionservice
  newName: matslo123/storefrontprojectionservice
  newTag: v0.7.0
  digest: sha256:13ff3ef9fb7a254e595f3ace2caad03b16384dbf1709843292f03a0b27d895af
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    boutique.online.io/region: us-east-1
    boutique.online.io/k8s-cluster: eks-cluster
patches:
- path: frontend-external.yaml
- path: benchmarkservice-external.yaml
- target: {group: apps, version: v1, kind: Deployment}
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target: {group: autoscaling, version: v2, kind: HorizontalPodAutoscaler}
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 1
- target: {group: apps, version: v1, kind: Deployment}
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OTEL_RESOURCE_ATTRIBUTES
        value: cloud.region=us-east-1,k8s.cluster.name=eks-cluster,nats.cluster.name=BOUTIQUE-us-east-1
- target: {group: apps, version: v1, kind: Deployment, name: storefrontprojectionservice}
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: storefront-projection-us-east-1-v1,boutique.qry.storefront.home.v1,boutique.qry.storefront.product.v1,boutique.qry.storefront.cart.v1,boutique.qry.storefront.currencies.v1,boutique.qry.storefront.product-meta.v1,boutique.qry.storefront.operation.v1,boutique.qry.storefront.order.v1
