apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- setup.yaml
- config.yaml
- statefulset.yaml
- bootstrap.yaml
- backup.yaml
- monitoring.yaml
- network-policy.yaml
- client-config.yaml
