apiVersion: builtin
kind: PatchTransformer
metadata: {name: remove-primary-serviceaccounts}
patch: |-
  apiVersion: v1
  kind: ServiceAccount
  metadata: {name: delete-selected-primary-serviceaccount}
  $patch: delete
target:
  version: v1
  kind: ServiceAccount
  name: adservice|benchmark-runner|benchmarkservice|cartservice|checkoutservice|currencyservice|emailservice|messageoperationsservice|productcatalogservice|recommendationservice|shippingservice
