# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: emailservice
    context: .
    docker:
      dockerfile: src/emailservice/Dockerfile
  - image: productcatalogservice
    context: .
    docker:
      dockerfile: src/productcatalogservice/Dockerfile
  - image: recommendationservice
    context: src/recommendationservice
  - image: shoppingassistantservice
    context: src/shoppingassistantservice
  - image: shippingservice
    context: .
    docker:
      dockerfile: src/shippingservice/Dockerfile
  - image: checkoutservice
    context: .
    docker:
      dockerfile: src/checkoutservice/Dockerfile
  - image: paymentservice
    context: .
    docker:
      dockerfile: src/paymentservice/Dockerfile
  - image: currencyservice
    context: .
    docker:
      dockerfile: src/currencyservice/Dockerfile
  - image: cartservice
    context: .
    docker:
      dockerfile: src/cartservice/src/Dockerfile
  - image: storefrontprojectionservice
    context: .
    docker:
      dockerfile: src/storefrontprojectionservice/Dockerfile
  - image: frontend
    context: .
    docker:
      dockerfile: src/frontend/Dockerfile
  - image: adservice
    context: .
    docker:
      dockerfile: src/adservice/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true
    useBuildkit: true
manifests:
  kustomize:
    paths:
    - kubernetes-manifests
deploy:
  kubectl: {}
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
profiles:
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
# "debug" profile replaces the default Dockerfile in cartservice with Dockerfile.debug,
# which enables debugging via skaffold.
#
# This profile is used by default when running skaffold debug.
- name: debug
  activation:
  - command: debug
  patches:
  - op: replace
    path: /build/artifacts/8/docker/dockerfile
    value: src/cartservice/src/Dockerfile.debug
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: loadgenerator
requires:
- configs:
  - app
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
  - image: loadgenerator
    context: src/loadgenerator
  local:
    useDockerCLI: true
    useBuildkit: true
manifests:
  rawYaml:
  - ./kubernetes-manifests/loadgenerator.yaml
deploy:
  kubectl: {}
profiles:
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
