<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.Tools" Version="2.80.0" PrivateAssets="All" />
    <PackageReference Include="NATS.Net" Version="3.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\stateless\dotnet\Boutique.Stateless\Boutique.Stateless.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="protos\Cart.proto" GrpcServices="None" />
    <Protobuf Include="..\..\..\protos\common\v1\message.proto" GrpcServices="None" ProtoRoot="..\..\.." Link="protos\common\v1\message.proto" />
    <Protobuf Include="..\..\..\protos\commands\v1\commands.proto" GrpcServices="None" ProtoRoot="..\..\.." Link="protos\commands\v1\commands.proto" />
    <Protobuf Include="..\..\..\protos\events\v1\events.proto" GrpcServices="None" ProtoRoot="..\..\.." Link="protos\events\v1\events.proto" />
  </ItemGroup>
</Project>
