apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../kubernetes-manifests
- client-config.yaml
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    boutique.online.io/region: local
    boutique.online.io/k8s-cluster: local
patches:
- target: {group: apps, version: v1, kind: Deployment}
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OTEL_RESOURCE_ATTRIBUTES
        value: cloud.region=local,k8s.cluster.name=local,nats.cluster.name=BOUTIQUE
