# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../single-replica-base
components:
- ../components/benchmark-resources
- ../components/no-tracing
- ../components/redis-retention
patches:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: redis-cart-cluster|redis-checkout-cluster
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: |-
        exec redis-server \
          --bind 0.0.0.0 \
          --protected-mode no \
          --port 6379 \
          --appendonly yes \
          --appendfsync always \
          --save ""
