# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../single-replica-base
components:
- ../components/benchmark-resources
- ../components/no-tracing
- ../components/redis-retention
