// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protos/commands/v1/commands.proto

package commandsv1

import (
	v1 "github.com/GoogleCloudPlatform/microservices-demo/protos/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartAddItemCommand struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CommandId           string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId           string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity            int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExpectedCartVersion uint64                 `protobuf:"varint,5,opt,name=expected_cart_version,json=expectedCartVersion,proto3" json:"expected_cart_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CartAddItemCommand) Reset() {
	*x = CartAddItemCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartAddItemCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartAddItemCommand) ProtoMessage() {}

func (x *CartAddItemCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartAddItemCommand.ProtoReflect.Descriptor instead.
func (*CartAddItemCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *CartAddItemCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CartAddItemCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartAddItemCommand) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartAddItemCommand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartAddItemCommand) GetExpectedCartVersion() uint64 {
	if x != nil {
		return x.ExpectedCartVersion
	}
	return 0
}

type CartClearCommand struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CommandId           string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpectedCartVersion uint64                 `protobuf:"varint,3,opt,name=expected_cart_version,json=expectedCartVersion,proto3" json:"expected_cart_version,omitempty"`
	Reason              string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	OrderId             string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CartClearCommand) Reset() {
	*x = CartClearCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartClearCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartClearCommand) ProtoMessage() {}

func (x *CartClearCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartClearCommand.ProtoReflect.Descriptor instead.
func (*CartClearCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CartClearCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CartClearCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartClearCommand) GetExpectedCartVersion() uint64 {
	if x != nil {
		return x.ExpectedCartVersion
	}
	return 0
}

func (x *CartClearCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CartClearCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderSubmitCommand struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CommandId               string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OperationId             string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OrderId                 string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                  string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpectedCartVersion     uint64                 `protobuf:"varint,5,opt,name=expected_cart_version,json=expectedCartVersion,proto3" json:"expected_cart_version,omitempty"`
	ExpectedCatalogRevision uint64                 `protobuf:"varint,6,opt,name=expected_catalog_revision,json=expectedCatalogRevision,proto3" json:"expected_catalog_revision,omitempty"`
	ExpectedRateRevision    uint64                 `protobuf:"varint,7,opt,name=expected_rate_revision,json=expectedRateRevision,proto3" json:"expected_rate_revision,omitempty"`
	CurrencyCode            string                 `protobuf:"bytes,8,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	ShippingAddress         *v1.PostalAddress      `protobuf:"bytes,9,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Email                   string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	PaymentToken            string                 `protobuf:"bytes,11,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OrderSubmitCommand) Reset() {
	*x = OrderSubmitCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSubmitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSubmitCommand) ProtoMessage() {}

func (x *OrderSubmitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSubmitCommand.ProtoReflect.Descriptor instead.
func (*OrderSubmitCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *OrderSubmitCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *OrderSubmitCommand) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OrderSubmitCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderSubmitCommand) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderSubmitCommand) GetExpectedCartVersion() uint64 {
	if x != nil {
		return x.ExpectedCartVersion
	}
	return 0
}

func (x *OrderSubmitCommand) GetExpectedCatalogRevision() uint64 {
	if x != nil {
		return x.ExpectedCatalogRevision
	}
	return 0
}

func (x *OrderSubmitCommand) GetExpectedRateRevision() uint64 {
	if x != nil {
		return x.ExpectedRateRevision
	}
	return 0
}

func (x *OrderSubmitCommand) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *OrderSubmitCommand) GetShippingAddress() *v1.PostalAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *OrderSubmitCommand) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrderSubmitCommand) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

type ShippingCalculateOrderQuoteCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingAddress *v1.PostalAddress      `protobuf:"bytes,3,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Cart            *v1.CartSnapshot       `protobuf:"bytes,4,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShippingCalculateOrderQuoteCommand) Reset() {
	*x = ShippingCalculateOrderQuoteCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCalculateOrderQuoteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCalculateOrderQuoteCommand) ProtoMessage() {}

func (x *ShippingCalculateOrderQuoteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCalculateOrderQuoteCommand.ProtoReflect.Descriptor instead.
func (*ShippingCalculateOrderQuoteCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *ShippingCalculateOrderQuoteCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ShippingCalculateOrderQuoteCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShippingCalculateOrderQuoteCommand) GetShippingAddress() *v1.PostalAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *ShippingCalculateOrderQuoteCommand) GetCart() *v1.CartSnapshot {
	if x != nil {
		return x.Cart
	}
	return nil
}

type ShippingCreateShipmentCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingAddress *v1.PostalAddress      `protobuf:"bytes,3,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Items           []*v1.CartLine         `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShippingCreateShipmentCommand) Reset() {
	*x = ShippingCreateShipmentCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCreateShipmentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCreateShipmentCommand) ProtoMessage() {}

func (x *ShippingCreateShipmentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCreateShipmentCommand.ProtoReflect.Descriptor instead.
func (*ShippingCreateShipmentCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{4}
}

func (x *ShippingCreateShipmentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ShippingCreateShipmentCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShippingCreateShipmentCommand) GetShippingAddress() *v1.PostalAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *ShippingCreateShipmentCommand) GetItems() []*v1.CartLine {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShippingCreateShipmentCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ShippingCancelShipmentCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShipmentId     string                 `protobuf:"bytes,3,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	TrackingId     string                 `protobuf:"bytes,4,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShippingCancelShipmentCommand) Reset() {
	*x = ShippingCancelShipmentCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCancelShipmentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCancelShipmentCommand) ProtoMessage() {}

func (x *ShippingCancelShipmentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCancelShipmentCommand.ProtoReflect.Descriptor instead.
func (*ShippingCancelShipmentCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{5}
}

func (x *ShippingCancelShipmentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ShippingCancelShipmentCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShippingCancelShipmentCommand) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShippingCancelShipmentCommand) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *ShippingCancelShipmentCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ShippingCancelShipmentCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PaymentAuthorizeCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount         *v1.Money              `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentToken   string                 `protobuf:"bytes,4,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentAuthorizeCommand) Reset() {
	*x = PaymentAuthorizeCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAuthorizeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAuthorizeCommand) ProtoMessage() {}

func (x *PaymentAuthorizeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAuthorizeCommand.ProtoReflect.Descriptor instead.
func (*PaymentAuthorizeCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentAuthorizeCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PaymentAuthorizeCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentAuthorizeCommand) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentAuthorizeCommand) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *PaymentAuthorizeCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PaymentCaptureCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AuthorizationId string                 `protobuf:"bytes,3,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	Amount          *v1.Money              `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentCaptureCommand) Reset() {
	*x = PaymentCaptureCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCaptureCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCaptureCommand) ProtoMessage() {}

func (x *PaymentCaptureCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCaptureCommand.ProtoReflect.Descriptor instead.
func (*PaymentCaptureCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentCaptureCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PaymentCaptureCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentCaptureCommand) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *PaymentCaptureCommand) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentCaptureCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PaymentReleaseAuthorizationCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AuthorizationId string                 `protobuf:"bytes,3,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentReleaseAuthorizationCommand) Reset() {
	*x = PaymentReleaseAuthorizationCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReleaseAuthorizationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReleaseAuthorizationCommand) ProtoMessage() {}

func (x *PaymentReleaseAuthorizationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReleaseAuthorizationCommand.ProtoReflect.Descriptor instead.
func (*PaymentReleaseAuthorizationCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentReleaseAuthorizationCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PaymentReleaseAuthorizationCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentReleaseAuthorizationCommand) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *PaymentReleaseAuthorizationCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PaymentReleaseAuthorizationCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type AssistantGenerateResponseCommand struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CommandId            string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OperationId          string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SessionId            string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt               string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ImageObjectReference string                 `protobuf:"bytes,5,opt,name=image_object_reference,json=imageObjectReference,proto3" json:"image_object_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssistantGenerateResponseCommand) Reset() {
	*x = AssistantGenerateResponseCommand{}
	mi := &file_protos_commands_v1_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantGenerateResponseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantGenerateResponseCommand) ProtoMessage() {}

func (x *AssistantGenerateResponseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protos_commands_v1_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantGenerateResponseCommand.ProtoReflect.Descriptor instead.
func (*AssistantGenerateResponseCommand) Descriptor() ([]byte, []int) {
	return file_protos_commands_v1_commands_proto_rawDescGZIP(), []int{9}
}

func (x *AssistantGenerateResponseCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AssistantGenerateResponseCommand) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AssistantGenerateResponseCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AssistantGenerateResponseCommand) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AssistantGenerateResponseCommand) GetImageObjectReference() string {
	if x != nil {
		return x.ImageObjectReference
	}
	return ""
}

var File_protos_commands_v1_commands_proto protoreflect.FileDescriptor

const file_protos_commands_v1_commands_proto_rawDesc = "" +
	"\n" +
	"!protos/commands/v1/commands.proto\x12\x14boutique.commands.v1\x1a\x1eprotos/common/v1/message.proto\"\xbb\x01\n" +
	"\x12CartAddItemCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x122\n" +
	"\x15expected_cart_version\x18\x05 \x01(\x04R\x13expectedCartVersion\"\xb1\x01\n" +
	"\x10CartClearCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\x15expected_cart_version\x18\x03 \x01(\x04R\x13expectedCartVersion\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\"\xde\x03\n" +
	"\x12OrderSubmitCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x122\n" +
	"\x15expected_cart_version\x18\x05 \x01(\x04R\x13expectedCartVersion\x12:\n" +
	"\x19expected_catalog_revision\x18\x06 \x01(\x04R\x17expectedCatalogRevision\x124\n" +
	"\x16expected_rate_revision\x18\a \x01(\x04R\x14expectedRateRevision\x12#\n" +
	"\rcurrency_code\x18\b \x01(\tR\fcurrencyCode\x12L\n" +
	"\x10shipping_address\x18\t \x01(\v2!.boutique.common.v1.PostalAddressR\x0fshippingAddress\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12#\n" +
	"\rpayment_token\x18\v \x01(\tR\fpaymentToken\"\xe2\x01\n" +
	"\"ShippingCalculateOrderQuoteCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12L\n" +
	"\x10shipping_address\x18\x03 \x01(\v2!.boutique.common.v1.PostalAddressR\x0fshippingAddress\x124\n" +
	"\x04cart\x18\x04 \x01(\v2 .boutique.common.v1.CartSnapshotR\x04cart\"\x84\x02\n" +
	"\x1dShippingCreateShipmentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12L\n" +
	"\x10shipping_address\x18\x03 \x01(\v2!.boutique.common.v1.PostalAddressR\x0fshippingAddress\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.boutique.common.v1.CartLineR\x05items\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xdc\x01\n" +
	"\x1dShippingCancelShipmentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vshipment_id\x18\x03 \x01(\tR\n" +
	"shipmentId\x12\x1f\n" +
	"\vtracking_id\x18\x04 \x01(\tR\n" +
	"trackingId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\xd4\x01\n" +
	"\x17PaymentAuthorizeCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x121\n" +
	"\x06amount\x18\x03 \x01(\v2\x19.boutique.common.v1.MoneyR\x06amount\x12#\n" +
	"\rpayment_token\x18\x04 \x01(\tR\fpaymentToken\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xd8\x01\n" +
	"\x15PaymentCaptureCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12)\n" +
	"\x10authorization_id\x18\x03 \x01(\tR\x0fauthorizationId\x121\n" +
	"\x06amount\x18\x04 \x01(\v2\x19.boutique.common.v1.MoneyR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xca\x01\n" +
	"\"PaymentReleaseAuthorizationCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12)\n" +
	"\x10authorization_id\x18\x03 \x01(\tR\x0fauthorizationId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xd1\x01\n" +
	" AssistantGenerateResponseCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x124\n" +
	"\x16image_object_reference\x18\x05 \x01(\tR\x14imageObjectReferenceB\x80\x01\n" +
	"\x14boutique.commands.v1P\x01ZOgithub.com/GoogleCloudPlatform/microservices-demo/protos/commands/v1;commandsv1\xaa\x02\x14Boutique.Commands.V1b\x06proto3"

var (
	file_protos_commands_v1_commands_proto_rawDescOnce sync.Once
	file_protos_commands_v1_commands_proto_rawDescData []byte
)

func file_protos_commands_v1_commands_proto_rawDescGZIP() []byte {
	file_protos_commands_v1_commands_proto_rawDescOnce.Do(func() {
		file_protos_commands_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_commands_v1_commands_proto_rawDesc), len(file_protos_commands_v1_commands_proto_rawDesc)))
	})
	return file_protos_commands_v1_commands_proto_rawDescData
}

var file_protos_commands_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_commands_v1_commands_proto_goTypes = []any{
	(*CartAddItemCommand)(nil),                 // 0: boutique.commands.v1.CartAddItemCommand
	(*CartClearCommand)(nil),                   // 1: boutique.commands.v1.CartClearCommand
	(*OrderSubmitCommand)(nil),                 // 2: boutique.commands.v1.OrderSubmitCommand
	(*ShippingCalculateOrderQuoteCommand)(nil), // 3: boutique.commands.v1.ShippingCalculateOrderQuoteCommand
	(*ShippingCreateShipmentCommand)(nil),      // 4: boutique.commands.v1.ShippingCreateShipmentCommand
	(*ShippingCancelShipmentCommand)(nil),      // 5: boutique.commands.v1.ShippingCancelShipmentCommand
	(*PaymentAuthorizeCommand)(nil),            // 6: boutique.commands.v1.PaymentAuthorizeCommand
	(*PaymentCaptureCommand)(nil),              // 7: boutique.commands.v1.PaymentCaptureCommand
	(*PaymentReleaseAuthorizationCommand)(nil), // 8: boutique.commands.v1.PaymentReleaseAuthorizationCommand
	(*AssistantGenerateResponseCommand)(nil),   // 9: boutique.commands.v1.AssistantGenerateResponseCommand
	(*v1.PostalAddress)(nil),                   // 10: boutique.common.v1.PostalAddress
	(*v1.CartSnapshot)(nil),                    // 11: boutique.common.v1.CartSnapshot
	(*v1.CartLine)(nil),                        // 12: boutique.common.v1.CartLine
	(*v1.Money)(nil),                           // 13: boutique.common.v1.Money
}
var file_protos_commands_v1_commands_proto_depIdxs = []int32{
	10, // 0: boutique.commands.v1.OrderSubmitCommand.shipping_address:type_name -> boutique.common.v1.PostalAddress
	10, // 1: boutique.commands.v1.ShippingCalculateOrderQuoteCommand.shipping_address:type_name -> boutique.common.v1.PostalAddress
	11, // 2: boutique.commands.v1.ShippingCalculateOrderQuoteCommand.cart:type_name -> boutique.common.v1.CartSnapshot
	10, // 3: boutique.commands.v1.ShippingCreateShipmentCommand.shipping_address:type_name -> boutique.common.v1.PostalAddress
	12, // 4: boutique.commands.v1.ShippingCreateShipmentCommand.items:type_name -> boutique.common.v1.CartLine
	13, // 5: boutique.commands.v1.PaymentAuthorizeCommand.amount:type_name -> boutique.common.v1.Money
	13, // 6: boutique.commands.v1.PaymentCaptureCommand.amount:type_name -> boutique.common.v1.Money
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_commands_v1_commands_proto_init() }
func file_protos_commands_v1_commands_proto_init() {
	if File_protos_commands_v1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_commands_v1_commands_proto_rawDesc), len(file_protos_commands_v1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_commands_v1_commands_proto_goTypes,
		DependencyIndexes: file_protos_commands_v1_commands_proto_depIdxs,
		MessageInfos:      file_protos_commands_v1_commands_proto_msgTypes,
	}.Build()
	File_protos_commands_v1_commands_proto = out.File
	file_protos_commands_v1_commands_proto_goTypes = nil
	file_protos_commands_v1_commands_proto_depIdxs = nil
}
