// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protos/common/v1/message.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageEnvelope is required around every command and durable domain event.
// Subject versions identify the payload contract; schema_version identifies
// this envelope contract and is 1 for the initial release.
type MessageEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType      string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	SchemaVersion    uint32                 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Producer         string                 `protobuf:"bytes,5,opt,name=producer,proto3" json:"producer,omitempty"`
	AggregateType    string                 `protobuf:"bytes,6,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId      string                 `protobuf:"bytes,7,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateVersion uint64                 `protobuf:"varint,8,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId      string                 `protobuf:"bytes,10,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	Traceparent      string                 `protobuf:"bytes,11,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate       string                 `protobuf:"bytes,12,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	Data             *anypb.Any             `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	mi := &file_protos_common_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEnvelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessageEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *MessageEnvelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *MessageEnvelope) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *MessageEnvelope) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *MessageEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *MessageEnvelope) GetAggregateVersion() uint64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

func (x *MessageEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *MessageEnvelope) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *MessageEnvelope) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *MessageEnvelope) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

func (x *MessageEnvelope) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// Failure contains only information safe to publish on integration subjects.
// Provider responses, stack traces, card data, and credentials are forbidden.
type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Retryable     bool                   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	SafeMessage   string                 `protobuf:"bytes,3,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_protos_common_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Failure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Failure) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Units         int64                  `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`
	Nanos         int32                  `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_protos_common_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type PostalAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreetAddress string                 `protobuf:"bytes,1,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	ZipCode       int32                  `protobuf:"varint,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostalAddress) Reset() {
	*x = PostalAddress{}
	mi := &file_protos_common_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostalAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostalAddress) ProtoMessage() {}

func (x *PostalAddress) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostalAddress.ProtoReflect.Descriptor instead.
func (*PostalAddress) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *PostalAddress) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *PostalAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PostalAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PostalAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PostalAddress) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type CartLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartLine) Reset() {
	*x = CartLine{}
	mi := &file_protos_common_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartLine) ProtoMessage() {}

func (x *CartLine) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartLine.ProtoReflect.Descriptor instead.
func (*CartLine) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *CartLine) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartLine) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartLine            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CartVersion   uint64                 `protobuf:"varint,3,opt,name=cart_version,json=cartVersion,proto3" json:"cart_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartSnapshot) Reset() {
	*x = CartSnapshot{}
	mi := &file_protos_common_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartSnapshot) ProtoMessage() {}

func (x *CartSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartSnapshot.ProtoReflect.Descriptor instead.
func (*CartSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *CartSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartSnapshot) GetItems() []*CartLine {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartSnapshot) GetCartVersion() uint64 {
	if x != nil {
		return x.CartVersion
	}
	return 0
}

type ProductSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture        string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	PriceUsd       *Money                 `protobuf:"bytes,5,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	Categories     []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	ProductVersion uint64                 `protobuf:"varint,7,opt,name=product_version,json=productVersion,proto3" json:"product_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductSnapshot) Reset() {
	*x = ProductSnapshot{}
	mi := &file_protos_common_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSnapshot) ProtoMessage() {}

func (x *ProductSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSnapshot.ProtoReflect.Descriptor instead.
func (*ProductSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *ProductSnapshot) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductSnapshot) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ProductSnapshot) GetPriceUsd() *Money {
	if x != nil {
		return x.PriceUsd
	}
	return nil
}

func (x *ProductSnapshot) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ProductSnapshot) GetProductVersion() uint64 {
	if x != nil {
		return x.ProductVersion
	}
	return 0
}

type OrderLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CartLine              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	UnitCost      *Money                 `protobuf:"bytes,2,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderLine) Reset() {
	*x = OrderLine{}
	mi := &file_protos_common_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLine) ProtoMessage() {}

func (x *OrderLine) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLine.ProtoReflect.Descriptor instead.
func (*OrderLine) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *OrderLine) GetItem() *CartLine {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *OrderLine) GetUnitCost() *Money {
	if x != nil {
		return x.UnitCost
	}
	return nil
}

type SanitizedOrderSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ShippingAddress *PostalAddress         `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Items           []*OrderLine           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	ShippingCost    *Money                 `protobuf:"bytes,6,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Total           *Money                 `protobuf:"bytes,7,opt,name=total,proto3" json:"total,omitempty"`
	TrackingId      string                 `protobuf:"bytes,8,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SanitizedOrderSnapshot) Reset() {
	*x = SanitizedOrderSnapshot{}
	mi := &file_protos_common_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizedOrderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizedOrderSnapshot) ProtoMessage() {}

func (x *SanitizedOrderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizedOrderSnapshot.ProtoReflect.Descriptor instead.
func (*SanitizedOrderSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *SanitizedOrderSnapshot) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SanitizedOrderSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SanitizedOrderSnapshot) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SanitizedOrderSnapshot) GetShippingAddress() *PostalAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *SanitizedOrderSnapshot) GetItems() []*OrderLine {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SanitizedOrderSnapshot) GetShippingCost() *Money {
	if x != nil {
		return x.ShippingCost
	}
	return nil
}

func (x *SanitizedOrderSnapshot) GetTotal() *Money {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *SanitizedOrderSnapshot) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type AdSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdSelection) Reset() {
	*x = AdSelection{}
	mi := &file_protos_common_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdSelection) ProtoMessage() {}

func (x *AdSelection) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdSelection.ProtoReflect.Descriptor instead.
func (*AdSelection) Descriptor() ([]byte, []int) {
	return file_protos_common_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *AdSelection) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *AdSelection) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_protos_common_v1_message_proto protoreflect.FileDescriptor

const file_protos_common_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1eprotos/common/v1/message.proto\x12\x12boutique.common.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x04\n" +
	"\x0fMessageEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\rR\rschemaVersion\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1a\n" +
	"\bproducer\x18\x05 \x01(\tR\bproducer\x12%\n" +
	"\x0eaggregate_type\x18\x06 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\a \x01(\tR\vaggregateId\x12+\n" +
	"\x11aggregate_version\x18\b \x01(\x04R\x10aggregateVersion\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\n" +
	" \x01(\tR\vcausationId\x12 \n" +
	"\vtraceparent\x18\v \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\f \x01(\tR\n" +
	"tracestate\x12(\n" +
	"\x04data\x18\r \x01(\v2\x14.google.protobuf.AnyR\x04data\"^\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\x12!\n" +
	"\fsafe_message\x18\x03 \x01(\tR\vsafeMessage\"X\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x05R\x05nanos\"\x95\x01\n" +
	"\rPostalAddress\x12%\n" +
	"\x0estreet_address\x18\x01 \x01(\tR\rstreetAddress\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x19\n" +
	"\bzip_code\x18\x05 \x01(\x05R\azipCode\"E\n" +
	"\bCartLine\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"~\n" +
	"\fCartSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x05items\x18\x02 \x03(\v2\x1c.boutique.common.v1.CartLineR\x05items\x12!\n" +
	"\fcart_version\x18\x03 \x01(\x04R\vcartVersion\"\x81\x02\n" +
	"\x0fProductSnapshot\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x126\n" +
	"\tprice_usd\x18\x05 \x01(\v2\x19.boutique.common.v1.MoneyR\bpriceUsd\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12'\n" +
	"\x0fproduct_version\x18\a \x01(\x04R\x0eproductVersion\"u\n" +
	"\tOrderLine\x120\n" +
	"\x04item\x18\x01 \x01(\v2\x1c.boutique.common.v1.CartLineR\x04item\x126\n" +
	"\tunit_cost\x18\x02 \x01(\v2\x19.boutique.common.v1.MoneyR\bunitCost\"\xf7\x02\n" +
	"\x16SanitizedOrderSnapshot\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12L\n" +
	"\x10shipping_address\x18\x04 \x01(\v2!.boutique.common.v1.PostalAddressR\x0fshippingAddress\x123\n" +
	"\x05items\x18\x05 \x03(\v2\x1d.boutique.common.v1.OrderLineR\x05items\x12>\n" +
	"\rshipping_cost\x18\x06 \x01(\v2\x19.boutique.common.v1.MoneyR\fshippingCost\x12/\n" +
	"\x05total\x18\a \x01(\v2\x19.boutique.common.v1.MoneyR\x05total\x12\x1f\n" +
	"\vtracking_id\x18\b \x01(\tR\n" +
	"trackingId\"D\n" +
	"\vAdSelection\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textBx\n" +
	"\x12boutique.common.v1P\x01ZKgithub.com/GoogleCloudPlatform/microservices-demo/protos/common/v1;commonv1\xaa\x02\x12Boutique.Common.V1b\x06proto3"

var (
	file_protos_common_v1_message_proto_rawDescOnce sync.Once
	file_protos_common_v1_message_proto_rawDescData []byte
)

func file_protos_common_v1_message_proto_rawDescGZIP() []byte {
	file_protos_common_v1_message_proto_rawDescOnce.Do(func() {
		file_protos_common_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_common_v1_message_proto_rawDesc), len(file_protos_common_v1_message_proto_rawDesc)))
	})
	return file_protos_common_v1_message_proto_rawDescData
}

var file_protos_common_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_common_v1_message_proto_goTypes = []any{
	(*MessageEnvelope)(nil),        // 0: boutique.common.v1.MessageEnvelope
	(*Failure)(nil),                // 1: boutique.common.v1.Failure
	(*Money)(nil),                  // 2: boutique.common.v1.Money
	(*PostalAddress)(nil),          // 3: boutique.common.v1.PostalAddress
	(*CartLine)(nil),               // 4: boutique.common.v1.CartLine
	(*CartSnapshot)(nil),           // 5: boutique.common.v1.CartSnapshot
	(*ProductSnapshot)(nil),        // 6: boutique.common.v1.ProductSnapshot
	(*OrderLine)(nil),              // 7: boutique.common.v1.OrderLine
	(*SanitizedOrderSnapshot)(nil), // 8: boutique.common.v1.SanitizedOrderSnapshot
	(*AdSelection)(nil),            // 9: boutique.common.v1.AdSelection
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*anypb.Any)(nil),              // 11: google.protobuf.Any
}
var file_protos_common_v1_message_proto_depIdxs = []int32{
	10, // 0: boutique.common.v1.MessageEnvelope.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 1: boutique.common.v1.MessageEnvelope.data:type_name -> google.protobuf.Any
	4,  // 2: boutique.common.v1.CartSnapshot.items:type_name -> boutique.common.v1.CartLine
	2,  // 3: boutique.common.v1.ProductSnapshot.price_usd:type_name -> boutique.common.v1.Money
	4,  // 4: boutique.common.v1.OrderLine.item:type_name -> boutique.common.v1.CartLine
	2,  // 5: boutique.common.v1.OrderLine.unit_cost:type_name -> boutique.common.v1.Money
	3,  // 6: boutique.common.v1.SanitizedOrderSnapshot.shipping_address:type_name -> boutique.common.v1.PostalAddress
	7,  // 7: boutique.common.v1.SanitizedOrderSnapshot.items:type_name -> boutique.common.v1.OrderLine
	2,  // 8: boutique.common.v1.SanitizedOrderSnapshot.shipping_cost:type_name -> boutique.common.v1.Money
	2,  // 9: boutique.common.v1.SanitizedOrderSnapshot.total:type_name -> boutique.common.v1.Money
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_common_v1_message_proto_init() }
func file_protos_common_v1_message_proto_init() {
	if File_protos_common_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_common_v1_message_proto_rawDesc), len(file_protos_common_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_common_v1_message_proto_goTypes,
		DependencyIndexes: file_protos_common_v1_message_proto_depIdxs,
		MessageInfos:      file_protos_common_v1_message_proto_msgTypes,
	}.Build()
	File_protos_common_v1_message_proto = out.File
	file_protos_common_v1_message_proto_goTypes = nil
	file_protos_common_v1_message_proto_depIdxs = nil
}
