apiVersion: builtin
kind: PatchTransformer
metadata: {name: remove-primary-role}
patch: |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata: {name: delete-selected-primary-role}
  $patch: delete
target:
  group: rbac.authorization.k8s.io
  version: v1
  kind: Role
  name: benchmarkservice-jobs
