# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: checkoutservice
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: checkoutservice
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                    - checkout-node
          tolerations:
          - key: dedicated
            operator: Equal
            value: checkoutservice
            effect: NoSchedule
- target:
    group: apps
    version: v1
    kind: Deployment
    name: currencyservice|productcatalogservice
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: unused
    spec:
      template:
        spec:
          containers:
          - name: server
            resources:
              requests:
                cpu: 100m
              limits:
                cpu: 500m
