apiVersion: v1
kind: ConfigMap
metadata: {name: nats-gateway-config, namespace: nats}
data:
  gateway.conf: |
    gateway {
      name: $NATS_CLUSTER_NAME
      listen: 0.0.0.0:7222
      advertise: $NATS_GATEWAY_ADVERTISE
      reject_unknown_cluster: true
      connect_retries: 120
      connect_backoff: true
      write_deadline: "10s"
      tls {
        cert_file: "/etc/nats/gateway-tls/tls.crt"
        key_file: "/etc/nats/gateway-tls/tls.key"
        ca_file: "/etc/nats/gateway-tls/ca.crt"
        min_version: "1.2"
        timeout: 5
        verify: true
      }
      gateways: [
        {
          name: "BOUTIQUE"
          urls: [
            tls://nats-0.gw.local.example.net:7222,
            tls://nats-1.gw.local.example.net:7222,
            tls://nats-2.gw.local.example.net:7222
          ]
        }
      ]
    }
