# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../kubernetes-manifests
components:
- ../components/no-tracing
