#!/usr/bin/env python3
"""Render the checked-in release and benchmark bundles deterministically."""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RELEASE_HEADER = """# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
#
# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# Generated by scripts/generate-release-manifests.py.
# ----------------------------------------------------------

# [START gke_release_kubernetes_manifests_microservices_demo]
---
"""
FOOTER = "# [END gke_release_kubernetes_manifests_microservices_demo]\n"
REGION_INVENTORY = ROOT / "kubernetes-manifests" / "regions" / "inventory.yaml"
SERVICES = (
    "adservice",
    "benchmarkservice",
    "cartservice",
    "checkoutservice",
    "currencyservice",
    "emailservice",
    "frontend",
    "loadgenerator",
    "messageoperationsservice",
    "paymentservice",
    "productcatalogservice",
    "recommendationservice",
    "shippingservice",
    "storefrontprojectionservice",
)
DEFAULT_IMAGE_DIGESTS = {
    "adservice": "3b307f7e2af68f8771807b3ca0dc80b75d341e1fd3464f96f7e8d8db5c2ae425",
    "benchmarkservice": "4c679cab7671ee42167f4691b72e17c0be20fc566b34ae4ab5cc6cbb9b6fd2e8",
    "cartservice": "e6788b26d4c34a769250a2a51c6378d5e3c96cda6c9cbe979e07c464e538ed07",
    "checkoutservice": "45d687649369e1bca4f49200b4fc6115e61730db14aa74cd385999582d890e2a",
    "currencyservice": "e4409286b69c8ccd3c287cce8d2ef0e0790f309be88e5353756e28bbffba9436",
    "emailservice": "703b889cefab8f7b720fa4680a1009f0a63388a19c8d79bade47117b9eedff9e",
    "frontend": "f85e899837a9e0f8ccdd87fb9ca73c8bdf1f391401bc4dca665dcb257e797101",
    "loadgenerator": "c66a188ecf8bf7507bd3982a5fa50ae3e9497f3239248dd48b275fc2aee0adb3",
    "messageoperationsservice": "2b2334e684a9297e2bf6af8daf0e924b86daecb78f9ff578756e9bc34b8f7a45",
    "paymentservice": "1ca91a6ed90cd8381172b9941d75c6d9d38fa9a53da82c4548cd1954a7125c23",
    "productcatalogservice": "26d97784a6e105cf1586b2ff723772c583021491d5fa165ceaae6a3af12fe54d",
    "recommendationservice": "3472c3ff064c23e7e9960e5700e6f25c1395acc9421ff6e6f09f3046e707a4a3",
    "shippingservice": "3ae7c7a3dc550a4e6f8d6fd9edcc312ce244b801cdf1405bc49cb5c507e8ed1b",
    "storefrontprojectionservice": "0733af933ce5f6745606cde5bface6b88b539ab51760a4b89995eb317e8ceb9d",
}


def render(path: str, *, allow_external_resources: bool = False) -> str:
    command = ["kubectl", "kustomize", path]
    if allow_external_resources:
        command.extend(["--load-restrictor", "LoadRestrictionsNone"])
    result = subprocess.run(
        command,
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return result.stdout.strip() + "\n"


def qualify_images(content: str) -> str:
    namespace = os.environ.get("DOCKERHUB_USERNAME", "matslo123")
    tag = os.environ.get("IMAGE_TAG", "v0.4.0")
    for service in SERVICES:
        reference = f"{namespace}/{service}:{tag}"
        if namespace == "matslo123" and tag == "v0.4.0":
            digest = DEFAULT_IMAGE_DIGESTS.get(service)
            if digest:
                reference += f"@sha256:{digest}"
        content = re.sub(
            rf"(?m)^(\s*image:\s*){re.escape(service)}\s*$",
            rf"\g<1>{reference}",
            content,
        )
    return content


def validate_regional_render(
    content: str, region: str, role: str, *, application: bool = False
) -> None:
    with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml") as manifest:
        manifest.write(content)
        manifest.flush()
        command = [
            sys.executable,
            "scripts/nats/validate-rendered.py",
            "--manifest",
            manifest.name,
            "--region",
            region,
            "--role",
            role,
        ]
        if application:
            command.append("--application")
        subprocess.run(command, cwd=ROOT, check=True)


def write(path: Path, content: str, header: str, footer: str = "") -> None:
    path.write_text(header + qualify_images(content) + footer)


def benchmark_header(
    description: str,
    notes: tuple[str, ...],
    *,
    requires_external_nats: bool = True,
) -> str:
    rendered_notes = "\n".join(f"# {line}" for line in notes)
    apply_instructions = (
        """# A default dynamic StorageClass is required.
# Install and wait for NATS before applying this benchmark bundle:
#   kubectl apply -k kubernetes-manifests/nats/benchmark
#   kubectl -n nats rollout status deployment/nats-setup --timeout=5m
#   kubectl -n nats rollout status statefulset/nats --timeout=10m
#   kubectl -n nats wait --for=condition=complete job/nats-global-bootstrap --timeout=10m
#   kubectl -n nats wait --for=condition=complete job/nats-regional-bootstrap --timeout=10m
#   kubectl apply -f <this-file>"""
        if requires_external_nats
        else """# Apply to a clean cluster with a default dynamic StorageClass:
#   kubectl apply -f <this-file>"""
    )
    return f"""# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
#
# {description}
#
# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# Generated by scripts/generate-release-manifests.py.
# ----------------------------------------------------------
#
{apply_instructions}
#
{rendered_notes}
---
"""


def main() -> None:
    subprocess.run(
        [
            sys.executable,
            "scripts/nats/validate-regions.py",
            "--inventory",
            str(REGION_INVENTORY),
        ],
        cwd=ROOT,
        check=True,
    )
    application = render("kubernetes-manifests")
    write(
        ROOT / "release" / "kubernetes-manifests-no-loadgenerator.yaml",
        application,
        RELEASE_HEADER,
        FOOTER,
    )
    loadgenerator = (
        ROOT / "kubernetes-manifests" / "loadgenerator.yaml"
    ).read_text()
    write(
        ROOT / "release" / "kubernetes-manifests.yaml",
        application + "---\n" + loadgenerator,
        RELEASE_HEADER,
        FOOTER,
    )
    hpa_application = render(
        "benchmark/manifests/hpa-application",
        allow_external_resources=True,
    )
    hpa_dependencies = render("benchmark/manifests/hpa-dependencies")
    target_metrics = render("benchmark/manifests/target-metrics")
    benchmark_application = render(
        "benchmark/manifests/fixed-replicas",
        allow_external_resources=True,
    )
    fixed_replica_application = render(
        "benchmark/manifests/single-replica",
        allow_external_resources=True,
    )
    release_single_replica_application = render(
        "benchmark/manifests/single-replica-base",
        allow_external_resources=True,
    )
    write(
        ROOT / "release" / "kubernetes-manifests-single-replica-no-loadgenerator.yaml",
        release_single_replica_application,
        RELEASE_HEADER,
        FOOTER,
    )
    delayed_application = render(
        "benchmark/manifests/with-delay",
        allow_external_resources=True,
    )
    fixed_replica_benchmark = (
        fixed_replica_application + "---\n" + target_metrics
    )
    benchmark = benchmark_application + "---\n" + target_metrics
    delayed_benchmark = delayed_application + "---\n" + target_metrics
    if delayed_benchmark.count("--appendfsync always") != 2:
        raise RuntimeError(
            "expected appendfsync configuration on both delayed benchmark "
            "Redis StatefulSets"
        )
    delayed_fsync1s_benchmark = delayed_benchmark.replace(
        "--appendfsync always", "--appendfsync everysec"
    )
    hpa_benchmark = (
        hpa_application
        + "---\n"
        + hpa_dependencies
        + "---\n"
        + target_metrics
    )
    benchmark_variants = {
        "benchmark-nats.yaml": (
            "Stateless NATS fixed-replica benchmark environment.",
            (
                "A compatible NATS configuration must already be running in the cluster.",
                "Every application service runs as two fixed replicas; Redis stores use",
                "their standalone single-replica topology. No application HPA is included.",
                "Run Locust on a separate cluster or host and point it at the external",
                "frontend and benchmarkmetrics URLs.",
                "The small in-cluster metrics gateway reports target-cluster resources.",
            ),
            fixed_replica_benchmark,
        ),
        "benchmark-nats-hpa.yaml": (
            "Stateless NATS autoscaling benchmark environment.",
            (
                "A compatible NATS configuration must already be running in the cluster.",
                "The application Deployments start with multiple rolling replicas and are",
                "governed by CPU and JetStream-lag HPAs. The bundle includes metrics-server,",
                "a benchmark Prometheus, recording rules, and Prometheus Adapter, so no",
                "cluster monitoring stack is required. Run Locust outside this cluster and use",
                "the external benchmarkmetrics URL to retain target-cluster resource samples.",
            ),
            hpa_benchmark,
        ),
        "benchmark-nats-multiple-replicas.yaml": (
            "Stateless NATS fixed-replica clustered-Redis benchmark environment.",
            (
                "A compatible NATS configuration must already be running in the cluster.",
                "The application Deployments run as two fixed replicas without HPAs and",
                "retain the clustered Redis topology and disruption budgets. Run Locust",
                "outside this cluster and use the external benchmarkmetrics URL to retain",
                "target-cluster resource samples.",
            ),
            benchmark,
        ),
        "benchmark-nats-with-delay.yaml": (
            "Stateless NATS benchmark environment with "
            "simulated provider latency.",
            (
                "A compatible NATS configuration must already be running in the cluster.",
                "This uses two fixed application replicas without HPAs and adds 500 ms of",
                "payment authorization latency plus 200 ms of shipment-creation latency.",
                "Run Locust outside this cluster and use the external benchmarkmetrics URL",
                "to retain target-cluster resource samples.",
            ),
            delayed_benchmark,
        ),
        "benchmark-nats-with-delay-fsync1s.yaml": (
            "Stateless NATS benchmark environment with "
            "simulated provider latency.",
            (
                "A compatible NATS configuration must already be running in the cluster.",
                "This uses two fixed application replicas without HPAs and adds 500 ms of",
                "payment authorization latency plus 200 ms of shipment-creation latency.",
                "Run Locust outside this cluster and use the external benchmarkmetrics URL",
                "to retain target-cluster resource samples.",
            ),
            delayed_fsync1s_benchmark,
        ),
    }
    for filename, (
        description,
        notes,
        content,
    ) in benchmark_variants.items():
        write(
            ROOT / "benchmark" / filename,
            content,
            benchmark_header(description, notes),
        )
    regional_release_dir = ROOT / "release" / "regions"
    regional_release_dir.mkdir(parents=True, exist_ok=True)
    inventory = json.loads(REGION_INVENTORY.read_text())
    for region in inventory["regions"]:
        region_id = region["region_id"]
        role = region["nats_cluster_role"]
        nats_mode = region["nats_mode"]
        nats_path = (
            f"kubernetes-manifests/nats/overlays/supercluster/{region_id}"
            if nats_mode == "supercluster"
            else "kubernetes-manifests/nats/overlays/standalone"
        )
        regional_application = render(
            f"regional-manifests/regions/{region_id}"
        )
        regional_nats = render(nats_path)
        validate_regional_render(regional_nats, region_id, role)
        validate_regional_render(
            regional_application, region_id, role, application=True
        )
        header = benchmark_header(
            f"Online Boutique regional release: {region_id} ({role}).",
            (
                f"Region identity: {region_id}.",
                f"NATS cluster role: {role}; topology mode: {nats_mode}.",
                "Apply only to the explicitly selected Kubernetes context for this region.",
            ),
            requires_external_nats=False,
        )
        write(
            regional_release_dir / f"{region_id}-{role}.yaml",
            regional_nats + "---\n" + regional_application,
            header,
        )
    print(
        "Generated release manifests with and without loadgenerator and "
        "the application-only NATS benchmark and per-region bundles."
    )


if __name__ == "__main__":
    main()
