#!/usr/bin/env python3
"""Render the checked-in release and NATS benchmark bundles deterministically."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RELEASE_HEADER = """# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
#
# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# Generated by scripts/generate-release-manifests.py.
# ----------------------------------------------------------

# [START gke_release_kubernetes_manifests_microservices_demo]
---
"""
FOOTER = "# [END gke_release_kubernetes_manifests_microservices_demo]\n"
SERVICES = (
    "adservice",
    "benchmarkservice",
    "cartservice",
    "checkoutservice",
    "currencyservice",
    "emailservice",
    "frontend",
    "loadgenerator",
    "paymentservice",
    "productcatalogservice",
    "recommendationservice",
    "shippingservice",
    "storefrontprojectionservice",
)
DEFAULT_IMAGE_DIGESTS = {
    "adservice": "ce4f217a588fed1d74f6a710e9c9ff3b3d9045f8219efe0aebb758eb2a831413",
    "benchmarkservice": "ff16cd2f0e927a1241fc4f7dae72945c365855eb7e04faf311a2e8955b105e93",
    "cartservice": "751cbd6b8fb98199757f722457853775304e51d20a57eae331cb60825dd524e2",
    "checkoutservice": "949a6a98bd4b24156e39fc60bf0bc1fdd4f9a5d7e381b1eef0ff7ed11c7e74fb",
    "currencyservice": "bcf569c32033a09c30fe9d7c5c6751c68ba43eb8f477dc1d069e1281b7c6100b",
    "emailservice": "bd6ae1930f8cd96a201830910f513595e1c4c47fec228a9a9c75241fab84698d",
    "frontend": "9fa9292420bea28f676fa7f237ed22d9949629f1e2c7a9dbf5baf372aaa5914f",
    "loadgenerator": "c66a188ecf8bf7507bd3982a5fa50ae3e9497f3239248dd48b275fc2aee0adb3",
    "paymentservice": "f5d0b3aeb1b032da3a5af9b64afc3a2688308d0818207735d18b51aad9807648",
    "productcatalogservice": "9721c7972d03c4c4b035c872f3b879c856f3016989f317a4b965878f547ecc41",
    "recommendationservice": "2f10eb25d40828c218dea63ae1ad323579d6204e5c49ace71c61b2bc84f9eabf",
    "shippingservice": "31edd6da1380d281f3b8c009191ada7bf230f66c3384fbd976701a4cb23e0453",
    "storefrontprojectionservice": "ca046da94f8c8da01622179dabb5cb24d1d7d9719b27cbb73ab383575335a469",
}


def render(path: str, *, allow_external_resources: bool = False) -> str:
    command = ["kubectl", "kustomize", path]
    if allow_external_resources:
        command.extend(["--load-restrictor", "LoadRestrictionsNone"])
    result = subprocess.run(
        command,
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return result.stdout.strip() + "\n"


def qualify_images(content: str) -> str:
    namespace = os.environ.get("DOCKERHUB_USERNAME", "matslo123")
    tag = os.environ.get("IMAGE_TAG", "v0.4.0")
    for service in SERVICES:
        reference = f"{namespace}/{service}:{tag}"
        if namespace == "matslo123" and tag == "v0.4.0":
            reference += f"@sha256:{DEFAULT_IMAGE_DIGESTS[service]}"
        content = re.sub(
            rf"(?m)^(\s*image:\s*){re.escape(service)}\s*$",
            rf"\g<1>{reference}",
            content,
        )
    return content


def write(path: Path, content: str, header: str, footer: str = "") -> None:
    path.write_text(header + qualify_images(content) + footer)


def benchmark_header(description: str, notes: tuple[str, ...]) -> str:
    rendered_notes = "\n".join(f"# {line}" for line in notes)
    return f"""# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
#
# {description}
#
# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# Generated by scripts/generate-release-manifests.py.
# ----------------------------------------------------------
#
# Apply to a clean cluster with a default dynamic StorageClass:
#   kubectl apply -f <this-file>
#
{rendered_notes}
---
"""


def main() -> None:
    application = render("kubernetes-manifests")
    write(
        ROOT / "release" / "kubernetes-manifests-no-loadgenerator.yaml",
        application,
        RELEASE_HEADER,
        FOOTER,
    )
    loadgenerator = (
        ROOT / "kubernetes-manifests" / "loadgenerator.yaml"
    ).read_text()
    write(
        ROOT / "release" / "kubernetes-manifests.yaml",
        application + "---\n" + loadgenerator,
        RELEASE_HEADER,
        FOOTER,
    )
    nats = render("kubernetes-manifests/nats/fresh-cluster")
    hpa_application = render("benchmark/manifests/hpa-application")
    hpa_dependencies = render("benchmark/manifests/hpa-dependencies")
    single_replica_application = render(
        "benchmark/manifests/single-replica",
        allow_external_resources=True,
    )
    single_replica_benchmark = nats + "---\n" + single_replica_application
    benchmark = nats + "---\n" + application
    hpa_benchmark = (
        nats
        + "---\n"
        + hpa_application
        + "---\n"
        + hpa_dependencies
    )
    benchmark_variants = {
        "benchmark-nats-single-replica.yaml": (
            "Self-contained stateless NATS single-replica benchmark "
            "environment.",
            (
                "Every application and Redis store runs as one fixed replica.",
                "NATS retains its replicated topology. Benchmark workloads run",
                "as disposable Jobs; run state and artifacts are held in",
                "replicated JetStream KV/Object Store buckets.",
            ),
            single_replica_benchmark,
        ),
        "benchmark-nats-hpa.yaml": (
            "Self-contained stateless NATS autoscaling benchmark environment.",
            (
                "The application Deployments start with multiple rolling replicas and are",
                "governed by CPU and JetStream-lag HPAs. The bundle includes metrics-server,",
                "a benchmark Prometheus, recording rules, and Prometheus Adapter, so no",
                "cluster monitoring stack is required. Benchmark workloads run as disposable",
                "Jobs; run state and artifacts are held in replicated JetStream KV/Object Store",
                "buckets.",
            ),
            hpa_benchmark,
        ),
        "benchmark-nats-multiple-replicas.yaml": (
            "Self-contained stateless NATS replica-scaling benchmark "
            "environment.",
            (
                "The application Deployments start with multiple rolling replicas and are",
                "governed by Phase 6 HPAs and disruption budgets. Benchmark workloads run as",
                "disposable Jobs; run state and artifacts are held in replicated JetStream",
                "KV/Object Store buckets.",
            ),
            benchmark,
        ),
    }
    for filename, (
        description,
        notes,
        content,
    ) in benchmark_variants.items():
        write(
            ROOT / "benchmark" / filename,
            content,
            benchmark_header(description, notes),
        )
    print(
        "Generated release manifests with and without loadgenerator and "
        "the NATS benchmark bundles."
    )


if __name__ == "__main__":
    main()
