apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../target-metrics
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: benchmarkmetrics
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: GRPC
