apiVersion: v1
kind: ConfigMap
metadata: {name: nats-client-config, namespace: default}
data:
  REGION_ID: us-west-2
  REGION_KEY: US_WEST_2
  K8S_CLUSTER_NAME: us-west-2-cluster
  NATS_CLUSTER_NAME: BOUTIQUE-us-west-2
  NATS_CLUSTER_ROLE: secondary
  STREAM_OWNER_REGION: eu-central-1
  NATS_SUPERCLUSTER_ENABLED: "true"
  STOREFRONT_PROJECTION_DURABLE: storefront-projection-us-west-2-v1
  STOREFRONT_PRODUCTS_BUCKET: STOREFRONT_PRODUCTS_US_WEST_2
  STOREFRONT_CARTS_BUCKET: STOREFRONT_CARTS_US_WEST_2
  STOREFRONT_CONTEXT_BUCKET: STOREFRONT_CONTEXT_US_WEST_2
  STOREFRONT_ORDERS_BUCKET: STOREFRONT_ORDERS_US_WEST_2
  STOREFRONT_OPERATIONS_BUCKET: STOREFRONT_OPERATIONS_US_WEST_2
  LIVE_OPERATION_PREFIX: boutique.live.operation.us-west-2.
  BENCHMARK_RUNS_BUCKET: BENCHMARK_RUNS_US_WEST_2
  BENCHMARK_ARTIFACTS_BUCKET: BENCHMARK_ARTIFACTS_US_WEST_2
