apiVersion: v1
kind: ConfigMap
metadata: {name: nats-global-bootstrap, namespace: nats}
$patch: delete
---
apiVersion: batch/v1
kind: Job
metadata: {name: nats-global-bootstrap, namespace: nats}
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: nats-backups, namespace: nats}
$patch: delete
---
apiVersion: batch/v1
kind: CronJob
metadata: {name: nats-backup, namespace: nats}
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: nats-advisory-watcher, namespace: nats}
$patch: delete
