apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
- gateway-services.yaml
- gateway-network-policy.yaml
patches:
- path: gateway-config.yaml
- path: region-config.yaml
- path: client-config.yaml
