apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-region-config
  namespace: nats
data:
  REGION_ID: us-east-1
  REGION_KEY: US_EAST_1
  K8S_CLUSTER_NAME: eks-cluster
  NATS_CLUSTER_NAME: BOUTIQUE-us-east-1
  NATS_CLUSTER_ROLE: primary
  NATS_SUPERCLUSTER_ENABLED: "true"
  STREAM_OWNER_REGION: us-east-1
  GLOBAL_ASSET_CLUSTER: BOUTIQUE-us-east-1
  NATS_REGION_TAG: region:us-east-1
  NATS_CLUSTER_TAG: cluster:BOUTIQUE-us-east-1
  NATS_GATEWAY_DOMAIN: elb.us-east-1.amazonaws.com
  NATS_GATEWAY_DNS_NAMES: k8s-nats-natsgate-20ecb3bc11-aecd78d3074202c8.elb.us-east-1.amazonaws.com,k8s-nats-natsgate-94d9321d7b-e1cc0fc025b842fd.elb.us-east-1.amazonaws.com,k8s-nats-natsgate-f5042541ac-3b35793a02898133.elb.us-east-1.amazonaws.com
  NATS_GATEWAY_ADVERTISE_0: k8s-nats-natsgate-20ecb3bc11-aecd78d3074202c8.elb.us-east-1.amazonaws.com:7222
  NATS_GATEWAY_ADVERTISE_1: k8s-nats-natsgate-94d9321d7b-e1cc0fc025b842fd.elb.us-east-1.amazonaws.com:7222
  NATS_GATEWAY_ADVERTISE_2: k8s-nats-natsgate-f5042541ac-3b35793a02898133.elb.us-east-1.amazonaws.com:7222
  STOREFRONT_EVENT_STREAM: BOUTIQUE_EVENTS
  STOREFRONT_PROJECTION_DURABLE: storefront-projection-us-east-1-v1
  STOREFRONT_PRODUCTS_BUCKET: STOREFRONT_PRODUCTS_US_EAST_1
  STOREFRONT_CARTS_BUCKET: STOREFRONT_CARTS_US_EAST_1
  STOREFRONT_CONTEXT_BUCKET: STOREFRONT_CONTEXT_US_EAST_1
  STOREFRONT_ORDERS_BUCKET: STOREFRONT_ORDERS_US_EAST_1
  STOREFRONT_OPERATIONS_BUCKET: STOREFRONT_OPERATIONS_US_EAST_1
  BENCHMARK_RUNS_BUCKET: BENCHMARK_RUNS_US_EAST_1
  BENCHMARK_ARTIFACTS_BUCKET: BENCHMARK_ARTIFACTS_US_EAST_1
  NATS_FRONTEND_LIVE_SUBJECT: boutique.live.operation.us-east-1.>
  NATS_PROJECTION_PRODUCTS_SUBJECT: $KV.STOREFRONT_PRODUCTS_US_EAST_1.>
  NATS_PROJECTION_CARTS_SUBJECT: $KV.STOREFRONT_CARTS_US_EAST_1.>
  NATS_PROJECTION_CONTEXT_SUBJECT: $KV.STOREFRONT_CONTEXT_US_EAST_1.>
  NATS_PROJECTION_ORDERS_SUBJECT: $KV.STOREFRONT_ORDERS_US_EAST_1.>
  NATS_PROJECTION_OPERATIONS_SUBJECT: $KV.STOREFRONT_OPERATIONS_US_EAST_1.>
  NATS_BENCHMARK_RUNS_SUBJECT: $KV.BENCHMARK_RUNS_US_EAST_1.>
  NATS_BENCHMARK_ARTIFACTS_SUBJECT: $O.BENCHMARK_ARTIFACTS_US_EAST_1.>
