apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
- gateway-services.yaml
- gateway-network-policy.yaml
patches:
- path: gateway-config.yaml
- path: region-config.yaml
- path: client-config.yaml
- path: remove-primary-control-plane.yaml
- path: scheduling.yaml
- target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: nats-operations-clients
  patch: |-
    - op: replace
      path: /spec/podSelector/matchExpressions/0/values
      value: [nats-regional-bootstrap]
