apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-region-config
  namespace: nats
data:
  REGION_ID: eu-central-1
  REGION_KEY: EU_CENTRAL_1
  K8S_CLUSTER_NAME: eu-central-1-cluster
  NATS_CLUSTER_NAME: BOUTIQUE-eu-central-1
  NATS_CLUSTER_ROLE: secondary
  NATS_SUPERCLUSTER_ENABLED: "true"
  STREAM_OWNER_REGION: us-east-1
  GLOBAL_ASSET_CLUSTER: BOUTIQUE-us-east-1
  NATS_REGION_TAG: region:eu-central-1
  NATS_CLUSTER_TAG: cluster:BOUTIQUE-eu-central-1
  NATS_GATEWAY_DOMAIN: elb.eu-central-1.amazonaws.com
  NATS_GATEWAY_DNS_NAMES: k8s-nats-natsgate-2c2a33a54d-a5259d04fb10ed85.elb.eu-central-1.amazonaws.com,k8s-nats-natsgate-8f9a9906cb-6a59ef3d4ff84f12.elb.eu-central-1.amazonaws.com,k8s-nats-natsgate-a22d86f61f-f6737fcb872d12be.elb.eu-central-1.amazonaws.com
  NATS_GATEWAY_ADVERTISE_0: k8s-nats-natsgate-2c2a33a54d-a5259d04fb10ed85.elb.eu-central-1.amazonaws.com:7222
  NATS_GATEWAY_ADVERTISE_1: k8s-nats-natsgate-8f9a9906cb-6a59ef3d4ff84f12.elb.eu-central-1.amazonaws.com:7222
  NATS_GATEWAY_ADVERTISE_2: k8s-nats-natsgate-a22d86f61f-f6737fcb872d12be.elb.eu-central-1.amazonaws.com:7222
  STOREFRONT_EVENT_STREAM: BOUTIQUE_EVENTS
  STOREFRONT_PROJECTION_DURABLE: storefront-projection-eu-central-1-v1
  STOREFRONT_PERSONALIZATION_STREAM: BOUTIQUE_PERSONALIZATION
  STOREFRONT_PERSONALIZATION_DURABLE: storefront-personalization-eu-central-1-v1
  STOREFRONT_PRODUCTS_BUCKET: STOREFRONT_PRODUCTS_EU_CENTRAL_1
  STOREFRONT_CARTS_BUCKET: STOREFRONT_CARTS_EU_CENTRAL_1
  STOREFRONT_CONTEXT_BUCKET: STOREFRONT_CONTEXT_EU_CENTRAL_1
  STOREFRONT_ORDERS_BUCKET: STOREFRONT_ORDERS_EU_CENTRAL_1
  STOREFRONT_OPERATIONS_BUCKET: STOREFRONT_OPERATIONS_EU_CENTRAL_1
  BENCHMARK_RUNS_BUCKET: BENCHMARK_RUNS_EU_CENTRAL_1
  BENCHMARK_ARTIFACTS_BUCKET: BENCHMARK_ARTIFACTS_EU_CENTRAL_1
  NATS_FRONTEND_LIVE_SUBJECT: boutique.live.operation.eu-central-1.>
  NATS_PROJECTION_PRODUCTS_SUBJECT: $KV.STOREFRONT_PRODUCTS_EU_CENTRAL_1.>
  NATS_PROJECTION_CARTS_SUBJECT: $KV.STOREFRONT_CARTS_EU_CENTRAL_1.>
  NATS_PROJECTION_CONTEXT_SUBJECT: $KV.STOREFRONT_CONTEXT_EU_CENTRAL_1.>
  NATS_PROJECTION_ORDERS_SUBJECT: $KV.STOREFRONT_ORDERS_EU_CENTRAL_1.>
  NATS_PROJECTION_OPERATIONS_SUBJECT: $KV.STOREFRONT_OPERATIONS_EU_CENTRAL_1.>
  NATS_BENCHMARK_RUNS_SUBJECT: $KV.BENCHMARK_RUNS_EU_CENTRAL_1.>
  NATS_BENCHMARK_ARTIFACTS_SUBJECT: $O.BENCHMARK_ARTIFACTS_EU_CENTRAL_1.>
